language: php

php:
  - 7.1

before_script:
  - composer install --no-interaction
  - sudo apt-get install ca-certificates
  - sudo curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem
  - export SSL_CERT_FILE=/usr/local/share/cacert.pem

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml