language: php

php:
  - 7.1

before_script:
  - composer install --no-interaction
  - sudo apt-get install --reinstall apt-transport-https ca-certificates -y
  - sudo update-ca-certificates

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover coverage.xml